### ISSUE TITLE
小程序后台显示异常 Cannot read properties of null (reading \'node\')

### ISSUE THREAD

**Issue by atjason** [lucaszhu2zgf/mp-progress#51]
你好，在小程序 We 分析后台 > 性能 > JS 里，会发现有类似下面的异常：

Cannot read properties of null (reading \'node\')
TypeError: Cannot read properties of null (reading \'node\')
at Object.<anonymous> (https://components/mp-progress/progress.min.js:2:2030)
at https://lib/WASubContext.js:1:417693
at pe (https://lib/WASubContext.js:1:294190)
at de (https://lib/WASubContext.js:1:293933)
at https://lib/WASubContext.js:1:294858

progress.min.js:2:2030 代码段，大概是下面的位置：

`i.select("#".concat(this._options.canvasId)).node(function(t){var e=t.node;`

希望能排查下是什么原因，

**Comment by lucaszhu2zgf** [comment]
> 你好，在小程序 We 分析后台 > 性能 > JS 里，会发现有类似下面的异常：
> 
> Cannot read properties of null (reading 'node') TypeError: Cannot read properties of null (reading 'node') at Object. (https://components/mp-progress/progress.min.js:2:2030) at https://lib/WASubContext.js:1:417693 at pe (https://lib/WASubContext.js:1:294190) at de (https://lib/WASubContext.js:1:293933) at https://lib/WASubContext.js:1:294858
> 
> progress.min.js:2:2030 代码段，大概是下面的位置：
> 
> `i.select("#".concat(this._options.canvasId)).node(function(t){var e=t.node;`
> 
> 希望能排查下是什么原因，

什么版本的基础库，有别的信息么

**Comment by atjason** [comment]
@lucaszhu2zgf 你好，我在 2030 的位置，加了 null 检查（`if(!t) return;`），暂时后台没有再报错了。

**Comment by lucaszhu2zgf** [comment]
> @lucaszhu2zgf 你好，我在 2030 的位置，加了 null 检查（`if(!t) return;`），暂时后台没有再报错了。

好的，准备发2.0版本，我会补充这个逻辑 @atjason
